# Tabla "Team_Attributes"

In [1]:
# HELPERS
import sqlite3 as sql
import pandas as pd

**Cargamos el Dataframe**

In [2]:
conn = sql.connect('../../data/database.sqlite')
query = 'SELECT * FROM Team_Attributes'
df = pd.read_sql_query(query, conn)

**Información Básica**

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              1458 non-null   int64
 1   team_fifa_api_id                1458 non-null   int64
 2   team_api_id                     1458 non-null   int64
 3   date                            1458 non-null   str
 4   buildUpPlaySpeed                1458 non-null   int64
 5   buildUpPlaySpeedClass           1458 non-null   str
 6   buildUpPlayDribbling            489 non-null    float64
 7   buildUpPlayDribblingClass       1458 non-null   str
 8   buildUpPlayPassing              1458 non-null   int64
 9   buildUpPlayPassingClass         1458 non-null   str
 10  buildUpPlayPositioningClass     1458 non-null   str
 11  chanceCreationPassing           1458 non-null   int64
 12  chanceCreationPassingClass      1458 non-null   str
 13  chanceCreationCrossing          1458 non-null   int64
 14  chanceCreationCrossingClass     1458 non-null   str
 15  chanceCreationShooting          1458 non-null   int64
 16  chanceCreationShootingClass     1458 non-null   str
 17  chanceCreationPositioningClass  1458 non-null   str
 18  defencePressure                 1458 non-null   int64
 19  defencePressureClass            1458 non-null   str
 20  defenceAggression               1458 non-null   int64
 21  defenceAggressionClass          1458 non-null   str
 22  defenceTeamWidth                1458 non-null   int64
 23  defenceTeamWidthClass           1458 non-null   str
 24  defenceDefenderLineClass        1458 non-null   str
dtypes: float64(1), int64(11), str(13)
memory usage: 419.6 KB

In [4]:
df.head()

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

In [5]:
df.describe(include='all')

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
count,1458.000000,1458.000000,1458.000000,1458,1458.000000,1458,489.000000,1458,1458.000000,1458,...,1458.000000,1458,1458,1458.000000,1458,1458.000000,1458,1458.000000,1458,1458
unique,NaN,NaN,NaN,6,NaN,3,NaN,3,NaN,3,...,NaN,3,2,NaN,3,NaN,3,NaN,3,2
top,NaN,NaN,NaN,2015-09-10 00:00:00,NaN,Balanced,NaN,Little,NaN,Mixed,...,NaN,Normal,Organised,NaN,Medium,NaN,Press,NaN,Normal,Cover
freq,NaN,NaN,NaN,245,NaN,1184,NaN,1004,NaN,1236,...,NaN,1224,1309,NaN,1243,NaN,1274,NaN,1286,1362
mean,729.500000,17706.982167,9995.727023,NaN,52.462277,NaN,48.607362,NaN,48.490398,NaN,...,53.969136,NaN,NaN,46.017147,NaN,49.251029,NaN,52.185871,NaN,NaN
std,421.032659,39179.857739,13264.869900,NaN,11.545869,NaN,9.678290,NaN,10.896101,NaN,...,10.327566,NaN,NaN,10.227225,NaN,9.738028,NaN,9.574712,NaN,NaN
min,1.000000,1.000000,1601.000000,NaN,20.000000,NaN,24.000000,NaN,20.000000,NaN,...,22.000000,NaN,NaN,23.000000,NaN,24.000000,NaN,29.000000,NaN,NaN
25%,365.250000,110.000000,8457.750000,NaN,45.000000,NaN,42.000000,NaN,40.000000,NaN,...,48.000000,NaN,NaN,39.000000,NaN,44.000000,NaN,47.000000,NaN,NaN
50%,729.500000,485.000000,8674.000000,NaN,52.000000,NaN,49.000000,NaN,50.000000,NaN,...,53.000000,NaN,NaN,45.000000,NaN,48.000000,NaN,52.000000,NaN,NaN
75%,1093.750000,1900.000000,9904.000000,NaN,62.000000,NaN,55.000000,NaN,55.000000,NaN,...,61.000000,NaN,NaN,51.000000,NaN,55.000000,NaN,58.000000,NaN,NaN
max,1458.000000,112513.000000,274581.000000,NaN,80.000000,NaN,77.000000,NaN,80.000000,NaN,...,80.000000,NaN,NaN,72.000000,NaN,72.000000,NaN,73.000000,NaN,NaN

In [6]:
df.shape

(1458, 25)

In [7]:
df.columns

Index(['id', 'team_fifa_api_id', 'team_api_id', 'date', 'buildUpPlaySpeed',
       'buildUpPlaySpeedClass', 'buildUpPlayDribbling',
       'buildUpPlayDribblingClass', 'buildUpPlayPassing',
       'buildUpPlayPassingClass', 'buildUpPlayPositioningClass',
       'chanceCreationPassing', 'chanceCreationPassingClass',
       'chanceCreationCrossing', 'chanceCreationCrossingClass',
       'chanceCreationShooting', 'chanceCreationShootingClass',
       'chanceCreationPositioningClass', 'defencePressure',
       'defencePressureClass', 'defenceAggression', 'defenceAggressionClass',
       'defenceTeamWidth', 'defenceTeamWidthClass',
       'defenceDefenderLineClass'],
      dtype='str')

In [8]:
df.isnull().sum()

id                                  0
team_fifa_api_id                    0
team_api_id                         0
date                                0
buildUpPlaySpeed                    0
buildUpPlaySpeedClass               0
buildUpPlayDribbling              969
buildUpPlayDribblingClass           0
buildUpPlayPassing                  0
buildUpPlayPassingClass             0
buildUpPlayPositioningClass         0
chanceCreationPassing               0
chanceCreationPassingClass          0
chanceCreationCrossing              0
chanceCreationCrossingClass         0
chanceCreationShooting              0
chanceCreationShootingClass         0
chanceCreationPositioningClass      0
defencePressure                     0
defencePressureClass                0
defenceAggression                   0
defenceAggressionClass              0
defenceTeamWidth                    0
defenceTeamWidthClass               0
defenceDefenderLineClass            0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)