# Tabla "Country"

In [16]:
# HELPERS
import sqlite3 as sql
import pandas as pd

**Cargamos el Dataframe**

In [17]:
conn = sql.connect('../../data/database.sqlite')
query = "SELECT * FROM Country"
df = pd.read_sql_query(query, conn)

**Información Básica**

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      11 non-null     int64
 1   name    11 non-null     str
dtypes: int64(1), str(1)
memory usage: 389.0 bytes

In [19]:
df.head()

      id     name
0      1  Belgium
1   1729  England
2   4769   France
3   7809  Germany
4  10257    Italy

In [20]:
df.describe(include='all')

                  id     name
count      11.000000       11
unique           NaN       11
top              NaN  Belgium
freq             NaN        1
mean    12452.090909      NaN
std      8215.308472      NaN
min         1.000000      NaN
25%      6289.000000      NaN
50%     13274.000000      NaN
75%     18668.000000      NaN
max     24558.000000      NaN

In [21]:
df.shape

(11, 2)

In [22]:
df.columns

Index(['id', 'name'], dtype='str')

In [23]:
df.isnull().sum()

id      0
name    0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)