# Tabla "Match"

In [41]:
# HELPERS
import sqlite3 as sql
import pandas as pd

**Cargamos Dataframe**

In [42]:
conn = sql.connect('../../data/database.sqlite')
query = "SELECT * FROM Match"
df = pd.read_sql_query(query, conn)

**Información Básica**

In [43]:
df.info(max_cols=120)

<class 'pandas.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Data columns (total 115 columns):
 #    Column            Non-Null Count  Dtype
---   ------            --------------  -----
 0    id                25979 non-null  int64
 1    country_id        25979 non-null  int64
 2    league_id         25979 non-null  int64
 3    season            25979 non-null  str
 4    stage             25979 non-null  int64
 5    date              25979 non-null  str
 6    match_api_id      25979 non-null  int64
 7    home_team_api_id  25979 non-null  int64
 8    away_team_api_id  25979 non-null  int64
 9    home_team_goal    25979 non-null  int64
 10   away_team_goal    25979 non-null  int64
 11   home_player_X1    24158 non-null  float64
 12   home_player_X2    24158 non-null  float64
 13   home_player_X3    24147 non-null  float64
 14   home_player_X4    24147 non-null  float64
 15   home_player_X5    24147 non-null  float64
 16   home_player_X6    24147 non-null  float64
 17   home_player_X7    24147 non-null  float64
 18   home_player_X8    24147 non-null  float64
 19   home_player_X9    24147 non-null  float64
 20   home_player_X10   24147 non-null  float64
 21   home_player_X11   24147 non-null  float64
 22   away_player_X1    24147 non-null  float64
 23   away_player_X2    24147 non-null  float64
 24   away_player_X3    24147 non-null  float64
 25   away_player_X4    24147 non-null  float64
 26   away_player_X5    24147 non-null  float64
 27   away_player_X6    24147 non-null  float64
 28   away_player_X7    24147 non-null  float64
 29   away_player_X8    24147 non-null  float64
 30   away_player_X9    24146 non-null  float64
 31   away_player_X10   24146 non-null  float64
 32   away_player_X11   24140 non-null  float64
 33   home_player_Y1    24158 non-null  float64
 34   home_player_Y2    24158 non-null  float64
 35   home_player_Y3    24147 non-null  float64
 36   home_player_Y4    24147 non-null  float64
 37   home_player_Y5    24147 non-null  float64
 38   home_player_Y6    24147 non-null  float64
 39   home_player_Y7    24147 non-null  float64
 40   home_player_Y8    24147 non-null  float64
 41   home_player_Y9    24147 non-null  float64
 42   home_player_Y10   24147 non-null  float64
 43   home_player_Y11   24147 non-null  float64
 44   away_player_Y1    24147 non-null  float64
 45   away_player_Y2    24147 non-null  float64
 46   away_player_Y3    24147 non-null  float64
 47   away_player_Y4    24147 non-null  float64
 48   away_player_Y5    24147 non-null  float64
 49   away_player_Y6    24147 non-null  float64
 50   away_player_Y7    24147 non-null  float64
 51   away_player_Y8    24147 non-null  float64
 52   away_player_Y9    24146 non-null  float64
 53   away_player_Y10   24146 non-null  float64
 54   away_player_Y11   24140 non-null  float64
 55   home_player_1     24755 non-null  float64
 56   home_player_2     24664 non-null  float64
 57   home_player_3     24698 non-null  float64
 58   home_player_4     24656 non-null  float64
 59   home_player_5     24663 non-null  float64
 60   home_player_6     24654 non-null  float64
 61   home_player_7     24752 non-null  float64
 62   home_player_8     24670 non-null  float64
 63   home_player_9     24706 non-null  float64
 64   home_player_10    24543 non-null  float64
 65   home_player_11    24424 non-null  float64
 66   away_player_1     24745 non-null  float64
 67   away_player_2     24701 non-null  float64
 68   away_player_3     24686 non-null  float64
 69   away_player_4     24658 non-null  float64
 70   away_player_5     24644 non-null  float64
 71   away_player_6     24666 non-null  float64
 72   away_player_7     24744 non-null  float64
 73   away_player_8     24638 non-null  float64
 74   away_player_9     24651 non-null  float64
 75   away_player_10    24538 non-null  float64
 76   away_player_11    24425 non-null  float64
 77   goal              14217 non-null  str
 78   shoton            14217 non-null  str
 79   shotoff           14217 non-null  str
 80   foulcommit        14217 non-null  str
 81   card              14217 non-null  str
 82   cross             14217 non-null  str
 83   corner            14217 non-null  str
 84   possession        14217 non-null  str
 85   B365H             22592 non-null  float64
 86   B365D             22592 non-null  float64
 87   B365A             22592 non-null  float64
 88   BWH               22575 non-null  float64
 89   BWD               22575 non-null  float64
 90   BWA               22575 non-null  float64
 91   IWH               22520 non-null  float64
 92   IWD               22520 non-null  float64
 93   IWA               22520 non-null  float64
 94   LBH               22556 non-null  float64
 95   LBD               22556 non-null  float64
 96   LBA               22556 non-null  float64
 97   PSH               11168 non-null  float64
 98   PSD               11168 non-null  float64
 99   PSA               11168 non-null  float64
 100  WHH               22571 non-null  float64
 101  WHD               22571 non-null  float64
 102  WHA               22571 non-null  float64
 103  SJH               17097 non-null  float64
 104  SJD               17097 non-null  float64
 105  SJA               17097 non-null  float64
 106  VCH               22568 non-null  float64
 107  VCD               22568 non-null  float64
 108  VCA               22568 non-null  float64
 109  GBH               14162 non-null  float64
 110  GBD               14162 non-null  float64
 111  GBA               14162 non-null  float64
 112  BSH               14161 non-null  float64
 113  BSD               14161 non-null  float64
 114  BSA               14161 non-null  float64
dtypes: float64(96), int64(9), str(10)
memory usage: 279.9 MB

In [44]:
df.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [45]:
df.describe(include='all')

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
count,25979.000000,25979.000000,25979.000000,25979,25979.000000,25979,2.597900e+04,25979.000000,25979.000000,25979.000000,25979.000000,24158.000000,24158.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.00000,24147.000000,24147.000000,24147.000000,24146.000000,24146.000000,24140.000000,24158.000000,24158.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.00000,24147.000000,24147.0,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24147.000000,24146.000000,24146.000000,24140.000000,24755.000000,24664.000000,24698.000000,24656.000000,24663.000000,24654.000000,24752.000000,24670.000000,24706.000000,24543.000000,24424.000000,24745.000000,24701.000000,24686.000000,24658.000000,24644.000000,24666.000000,24744.000000,24638.000000,24651.000000,24538.000000,24425.000000,14217,14217,14217,14217,14217,14217,14217,14217,22592.000000,22592.000000,22592.000000,22575.000000,22575.000000,22575.000000,22520.000000,22520.000000,22520.000000,22556.000000,22556.000000,22556.000000,11168.000000,11168.000000,11168.000000,22571.000000,22571.000000,22571.000000,17097.000000,17097.000000,17097.000000,22568.000000,22568.000000,22568.000000,14162.000000,14162.000000,14162.000000,14161.000000,14161.000000,14161.000000
unique,NaN,NaN,NaN,8,NaN,1694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13225,8464,8464,8466,13777,8466,8465,8420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,2008/2009,NaN,2009-04-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<goal />,<shoton />,<shotoff />,<foulcommit />,<card />,<cross />,<corner />,<possession />,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,3326,NaN,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,993,5754,5754,5752,441,5752,5753,5798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,12990.000000,11738.630317,11738.630317,NaN,18.242773,NaN,1.195429e+06,9984.371993,9984.475115,1.544594,1.160938,0.999586,2.073516,4.061001,6.049199,7.544871,3.185158,4.769909,5.309604,5.822048,5.389407,5.783244,1.000290,2.074585,4.058558,6.052222,7.52549,3.195387,4.742660,5.294115,5.807546,5.476187,5.766114,0.999627,2.998634,3.000083,3.000414,3.237214,6.476954,6.672257,7.238953,8.026339,9.218868,10.43699,1.000248,3.0,3.000166,3.000248,3.245124,6.469706,6.680292,7.246366,8.022115,9.161186,10.455178,76638.362432,106854.091996,91601.289457,94540.204494,109527.842071,102308.768516,97287.636918,107290.992947,111131.536914,105612.508373,103413.870660,76628.199879,107614.617424,91126.781293,95083.910617,109800.936901,102308.262588,97898.056014,109265.114214,111087.003448,107149.115943,104932.876970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.628818,3.839684,4.662222,2.559245,3.747597,4.396949,2.467613,3.608932,4.150575,2.536202,3.711740,4.385351,2.816447,4.132324,4.972744,2.578737,3.665295,4.482585,2.566061,3.755879,4.622343,2.668107,3.899048,4.840281,2.498764,3.648189,4.353097,2.497894,3.660742,4.405663
std,7499.635658,7553.936759,7553.936759,NaN,10.407354,NaN,4.946279e+05,14087.453758,14087.445135,1.297158,1.142110,0.022284,0.387185,0.385973,0.446024,1.609682,1.233609,1.092386,1.687376,1.968550,1.492068,0.759585,0.033438,0.403572,0.387047,0.448413,1.63765,1.284060,1.118226,1.687324,1.957116,1.541351,0.763611,0.024916,0.064003,0.012871,0.028777,0.940481,0.739988,0.588560,0.588947,1.126462,1.073893,0.50578,0.022292,0.0,0.025741,0.028779,0.955398,0.756391,0.586502,0.579881,1.126282,1.102167,0.498745,87556.226324,112619.266880,102703.003558,102789.967205,112787.542376,111514.726490,107050.579262,114527.022010,116221.869480,111528.262892,108761.188832,87428.953151,113758.447918,101438.583414,103845.905029,112450.715516,110861.276758,107359.030969,116358.092456,116492.957656,112397.540326,110237.525957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.794463,1.118269,3.730104,1.637983,1.033468,3.292265,1.445642,0.803582,2.858912,1.640648,1.003846,3.398285,2.187924,1.516680,4.475458,1.685725,0.958069,3.585083,1.655535,0.999582,3.632164,1.928753,1.248221,4.318338,1.489299,0.867440,3.010189,1.507793,0.868272,3.189814
min,1.000000,1.000000,1.000000,NaN,1.000000,NaN,4.831290e+05,1601.000000,1601.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000,3.000000,1.00000,1.000000,3.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,5.000000,6.000000,7.000000,2984.000000,2802.000000,2752.000000,2752.000000,2752.000000,2625.000000,2625.000000,2625.000000,2625.000000,2625.000000,2802.000000,2796.000000,2790.000000,2752.000000,2752.000000,2790.000000,2625.000000,2625.000000,2625.000000,2625.000000,2770.000000,2802.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.040000,1.400000,1.080000,1.030000,1.650000,1.100000,1.030000,1.500000,1.100000,1.040000,1.400000,1.100000,1.040000,2.200000,1.090000,1.020000,1.020000,1.080000,1.040000,1.400000,1.100000,1.030000,1.620000,1.080000,1.050000,1.450000,1.120000,1.040000,1.330000,1.120000
25%,6495.500000,4769.000000,4769.000000,NaN,9.000000,NaN,7.684365e+05,8475.000000,8475.000000,1.000000,0.000000,1.000000,2.000000,4.000000,6.000000,8.000000,2.000000,4.000000,3.000000,5.000000,4.000000,5.000000,1.000000,2.000000,4.000000,6.000000,8.00000,2.000000,4.000000,3.000000,5.000000,4.000000,5.000000,1.000000,3.000000,3.000000,3.000000,3.000000,6.000000,6.000000,7.000000,7.000000,8.000000,10.00000,1.000000,3.0,3.000000,3.000000,3.000000,6.000000,6.000000,7.000000,7.000000,8.000000,10.000000,30602.000000,32574.000000,30602.000000,30627.000000,33579.000000,31037.000000,30895.000000,32751.000000,33332.250000,32465.000000,32627.000000,30622.000000,32579.000000,30464.000000,30627.000000,33453.500000,31037.000000,30920.000000,32863.000000,33435.000000,32627.000000,32747.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.670000,3.300000,2.500000,1.650000,3.200000,2.500000,1.650000,3.200000,2.500000,1.670000,3.200000,2.500000,1.720000,3.410000,2.560000,1.670000,3.200000,2.500000,1.670000,3.250000,2.500000,1.700000,3.300000,2.550000,1.670000,3.200000,2.500000,1.670000,3.250000,2.500000
50%,12990.000000,10257.000000,10257.000000,NaN,18.000000,NaN,1.147511e+06,8697.000000,8697.000000,1.000000,1.000000,1.000000,2.000000,4.000000,6.000000,8.000000,3.000000,5.000000,6.000000,5.000000,5.000000,6.000000,1.000000,2.000000,4.000000,6.000000,8.00000,3.000000,5.000000,6.000000,5.000000,5.000000,6.000000,1.000000,3.000000,3.000000,3.000000,3.000000,7.000000,7.000000,7.000000,8.000000,10.000000,10.00000,1.000000,3.0,3.000000,3.000000,3.000000,7.000000,7.000000,7.000000,8.000000,10.000000,10.000000,38230.000000,42388.000000,39731.000000,41060.000000,45996.000000,41467.000000,41432.000000,43319.000000,45605.000000,43296.000000,42091.000000,38289.000000,42388.000000,39892.000000,41083.000000,46212.000000,41634.500000,41433.000000,45816.000000,45860.000000,45358.000000,42652.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.100000,3.500000,3.500000,2.100000,3.400000,3.400000,2.100000,3.300000,3.300000,2.100000,3.400000,3.300000,2.200000,3.640000,3.610000,2.150000,3.300000,3.400000,2.100000,3.400000,3.500000,2.150000,3.500000,3.500000,2.100000,3.300000,3.400000,2.100000,3.400000,3.400000
75%,19484.500000,17642.000000,17642.000000,NaN,27.000000,NaN,1.709852e+06,9925.000000,9925.000000,2.000000,2.000000,1.000000,2.000000,4.000000,6.000000,8.000000,4.000000,6.000000,7.000000,8.000000,7.000000,6.000000,1.000000,2.000000,4.000000,6.000000,8.00000,4.000000,6.000000,7.000000,8.000000,7.000000,6.000000,1.000000,3.000000,3.000000,3.000000,3.000000,7.000000,7.000000,8.000000,8.000000,10.000000,11.00000,1.000000,3.0,3.000000,3.000000,3.000000,7.000000,7.000000,8.000000,8.000000,10.000000,11.000000,96836.000000,159854.000000,128036.750000,145561.000000,160243.000000,150944.000000,141699.000000,160243.000000,164479.000000,158783.000000,161291.000000,96836.000000,159882.000000,121080.000000,145561.000000,160844.000000,151079.000000,144996.000000,163611.750000,164209.000000,161291.000000,161660.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.800000,4.000000,5.250000,2.750000,3.800000,5.000000,2.600000,3.700000,4.600000,2.700000,3.750000,5.000000,2.980000,4.230000,5.410000,2.750000,3.750000,5.000000,2.750000,3.800000,5.250000,2.800000,4.000000,5.400000,2.650000,3.750000,5.000000,2.620000,3.750000,5.000000
max,25979.000000,24558.000000,24558.000000,NaN,38.000000,NaN,2.216672e+06,274581.000000,274581.000000,10.000000,9.000000,2.000000,8.000000,8.000000,8.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,7.000000,6.000000,8.000000,9.000000,8.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,8.000000,3.000000,3.000000,5.000000,5.000000,8.000000,9.000000,9.000000,10.000000,10.000000,11.000000,11.00000,3.000000,3.0,7.000000,7.000000,9.000000,10.000000,10.000000,10.000000,11.000000,11.000000,11.000000,698273.000000,748432.000000,705484.000000,723037.000000,733787.000000,750584.000000,692984.000000,693171.000000,730065.000000,742405.000000,726956.000000,698273.000000,748432.000000,705484.000000,728414.000000,746419.000000,722766.000000,750435.000000,717248.000000,722766.000000,722766.000000,726956.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.000000,17.000000,51.000000,34.000000,19.500000,51.000000,20.000000,11.000000,25.000000,26.000000,19.000000,51.000000,36.000000,29.000000,47.500000,26.000000,17.000000,51.000000,23.000000,15.000000,41.000000,36.000000,26.000000,67.000000,21.000000,11.000000,34.000000,17.000000,13.000000,34.000000

In [46]:
df.shape

(25979, 115)

In [47]:
print(list(df.columns))

['id', 'country_id', 'league_id', 'season', 'stage', 'date', 'match_api_id', 'home_team_api_id', 'away_team_api_id', 'home_team_goal', 'away_team_goal', 'home_player_X1', 'home_player_X2', 'home_player_X3', 'home_player_X4', 'home_player_X5', 'home_player_X6', 'home_player_X7', 'home_player_X8', 'home_player_X9', 'home_player_X10', 'home_player_X11', 'away_player_X1', 'away_player_X2', 'away_player_X3', 'away_player_X4', 'away_player_X5', 'away_player_X6', 'away_player_X7', 'away_player_X8', 'away_player_X9', 'away_player_X10', 'away_player_X11', 'home_player_Y1', 'home_player_Y2', 'home_player_Y3', 'home_player_Y4', 'home_player_Y5', 'home_player_Y6', 'home_player_Y7', 'home_player_Y8', 'home_player_Y9', 'home_player_Y10', 'home_player_Y11', 'away_player_Y1', 'away_player_Y2', 'away_player_Y3', 'away_player_Y4', 'away_player_Y5', 'away_player_Y6', 'away_player_Y7', 'away_player_Y8', 'away_player_Y9', 'away_player_Y10', 'away_player_Y11', 'home_player_1', 'home_player_2', 'home_player_3', 'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7', 'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11', 'away_player_1', 'away_player_2', 'away_player_3', 'away_player_4', 'away_player_5', 'away_player_6', 'away_player_7', 'away_player_8', 'away_player_9', 'away_player_10', 'away_player_11', 'goal', 'shoton', 'shotoff', 'foulcommit', 'card', 'cross', 'corner', 'possession', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA']

In [48]:
print(df.isnull().sum().to_string())

id                      0
country_id              0
league_id               0
season                  0
stage                   0
date                    0
match_api_id            0
home_team_api_id        0
away_team_api_id        0
home_team_goal          0
away_team_goal          0
home_player_X1       1821
home_player_X2       1821
home_player_X3       1832
home_player_X4       1832
home_player_X5       1832
home_player_X6       1832
home_player_X7       1832
home_player_X8       1832
home_player_X9       1832
home_player_X10      1832
home_player_X11      1832
away_player_X1       1832
away_player_X2       1832
away_player_X3       1832
away_player_X4       1832
away_player_X5       1832
away_player_X6       1832
away_player_X7       1832
away_player_X8       1832
away_player_X9       1833
away_player_X10      1833
away_player_X11      1839
home_player_Y1       1821
home_player_Y2       1821
home_player_Y3       1832
home_player_Y4       1832
home_player_Y5       1832
home_player_Y6       1832
home_player_Y7       1832
home_player_Y8       1832
home_player_Y9       1832
home_player_Y10      1832
home_player_Y11      1832
away_player_Y1       1832
away_player_Y2       1832
away_player_Y3       1832
away_player_Y4       1832
away_player_Y5       1832
away_player_Y6       1832
away_player_Y7       1832
away_player_Y8       1832
away_player_Y9       1833
away_player_Y10      1833
away_player_Y11      1839
home_player_1        1224
home_player_2        1315
home_player_3        1281
home_player_4        1323
home_player_5        1316
home_player_6        1325
home_player_7        1227
home_player_8        1309
home_player_9        1273
home_player_10       1436
home_player_11       1555
away_player_1        1234
away_player_2        1278
away_player_3        1293
away_player_4        1321
away_player_5        1335
away_player_6        1313
away_player_7        1235
away_player_8        1341
away_player_9        1328
away_player_10       1441
away_player_11       1554
goal                11762
shoton              11762
shotoff             11762
foulcommit          11762
card                11762
cross               11762
corner              11762
possession          11762
B365H                3387
B365D                3387
B365A                3387
BWH                  3404
BWD                  3404
BWA                  3404
IWH                  3459
IWD                  3459
IWA                  3459
LBH                  3423
LBD                  3423
LBA                  3423
PSH                 14811
PSD                 14811
PSA                 14811
WHH                  3408
WHD                  3408
WHA                  3408
SJH                  8882
SJD                  8882
SJA                  8882
VCH                  3411
VCD                  3411
VCA                  3411
GBH                 11817
GBD                 11817
GBA                 11817
BSH                 11818
BSD                 11818
BSA                 11818

In [49]:
df.duplicated().sum()

np.int64(0)