# Tabla "League"

In [18]:
# HELPERS
import sqlite3 as sql
import pandas as pd

**Cargamos el Dataframe**

In [19]:
conn = sql.connect('../../data/database.sqlite')
query = "SELECT * FROM League"
df = pd.read_sql_query(query, conn)

**Información Básica**

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          11 non-null     int64
 1   country_id  11 non-null     int64
 2   name        11 non-null     str
dtypes: int64(2), str(1)
memory usage: 614.0 bytes

In [21]:
df.head()

      id  country_id                    name
0      1           1  Belgium Jupiler League
1   1729        1729  England Premier League
2   4769        4769          France Ligue 1
3   7809        7809   Germany 1. Bundesliga
4  10257       10257           Italy Serie A

In [22]:
df.describe(include='all')

                  id    country_id                    name
count      11.000000     11.000000                      11
unique           NaN           NaN                      11
top              NaN           NaN  Belgium Jupiler League
freq             NaN           NaN                       1
mean    12452.090909  12452.090909                     NaN
std      8215.308472   8215.308472                     NaN
min         1.000000      1.000000                     NaN
25%      6289.000000   6289.000000                     NaN
50%     13274.000000  13274.000000                     NaN
75%     18668.000000  18668.000000                     NaN
max     24558.000000  24558.000000                     NaN

In [23]:
df.shape

(11, 3)

In [24]:
df.columns

Index(['id', 'country_id', 'name'], dtype='str')

In [25]:
df.isnull().sum()

id            0
country_id    0
name          0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(0)