# Tabla "Team"

In [3]:
# HELPERS
import sqlite3 as sql
import pandas as pd

**Cargamos el Dataframe**

In [4]:
conn = sql.connect('../../data/database.sqlite')
query = 'SELECT * FROM Team'
df = pd.read_sql_query(query, conn)

**Información Básica**

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                299 non-null    int64
 1   team_api_id       299 non-null    int64
 2   team_fifa_api_id  288 non-null    float64
 3   team_long_name    299 non-null    str
 4   team_short_name   299 non-null    str
dtypes: float64(1), int64(2), str(2)
memory usage: 16.4 KB

In [6]:
df.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [7]:
df.describe(include='all')

,id,team_api_id,team_fifa_api_id,team_long_name,team_short_name
count,299.000000,299.000000,288.000000,299,299
unique,NaN,NaN,NaN,296,259
top,NaN,NaN,NaN,Royal Excel Mouscron,GEN
freq,NaN,NaN,NaN,2,3
mean,23735.301003,12340.521739,21534.305556,NaN,NaN
std,15167.914719,25940.411135,42456.439408,NaN,NaN
min,1.000000,1601.000000,1.000000,NaN,NaN
25%,9552.500000,8349.000000,178.750000,NaN,NaN
50%,22805.000000,8655.000000,673.500000,NaN,NaN
75%,36250.500000,9886.500000,1910.750000,NaN,NaN
max,51606.000000,274581.000000,112513.000000,NaN,NaN

In [8]:
df.shape

(299, 5)

In [9]:
df.columns

Index(['id', 'team_api_id', 'team_fifa_api_id', 'team_long_name',
       'team_short_name'],
      dtype='str')

In [10]:
df.isnull().sum()

id                   0
team_api_id          0
team_fifa_api_id    11
team_long_name       0
team_short_name      0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)